name: compileActions

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian
        compiler:
          - llvm-15.0.7
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/vcpkg
            ./build/vcpkg_installed
            ${{ env.HOME }}/.cache/vcpkg/archives
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ${{ env.LOCALAPPDATA }}\vcpkg\archives
            ${{ env.APPDATA }}\vcpkg\archives
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
          restore-keys: |
              ${{ runner.os }}-${{ env.BUILD_TYPE }}-
      - name: setup cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true
          vcpkg: true
          cppcheck: true
          clangtidy: true
          make: true
      - name: install deps and vcpkg package(Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y pkg-config ninja-build
          cd ~/vcpkg
          ./vcpkg install libhv
          ./vcpkg install glog
      - name: run cmake
        run: |
          cd ${{ github.workspace }}
          mkdir build && cd build
          cmake -B . -S .. -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15
      - name: build release
        run: |
          cd ${{ github.workspace }}/build
          cmake --build .
      - name: upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            ${{ github.workspace }}/build/electronBuzzer